// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetShop.Api.Infrastructure.Persistence;

#nullable disable

namespace PetShop.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PetShopDbContext))]
    [Migration("20260720200107_AddTutoresPersistence")]
    partial class AddTutoresPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetShop.Tutores.Domain.Tutor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Documento")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("InativadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inativado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.Property<string>("Telefone")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("telefone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tutores");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tutores_tenant_id");

                    b.HasIndex("TenantId", "Documento")
                        .IsUnique()
                        .HasDatabaseName("ix_tutores_tenant_id_documento");

                    b.ToTable("tutores", null, t =>
                        {
                            t.HasCheckConstraint("ck_tutores_contato_obrigatorio", "email IS NOT NULL OR telefone IS NOT NULL");

                            t.HasCheckConstraint("ck_tutores_documento_len", "documento IS NULL OR length(documento) = 11");

                            t.HasCheckConstraint("ck_tutores_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_tutores_situacao", "situacao IN (1, 2)");

                            t.HasCheckConstraint("ck_tutores_telefone_len", "telefone IS NULL OR length(telefone) IN (10, 11)");

                            t.HasCheckConstraint("ck_tutores_tenant_id_not_empty", "tenant_id <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
