// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetShop.Api.Infrastructure.Persistence;

#nullable disable

namespace PetShop.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PetShopDbContext))]
    partial class PetShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetShop.Tutores.Domain.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("CorOuPelagem")
                        .HasColumnType("text")
                        .HasColumnName("cor_ou_pelagem");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("DataDeNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_de_nascimento");

                    b.Property<DateOnly?>("DataDoFalecimento")
                        .HasColumnType("date")
                        .HasColumnName("data_do_falecimento");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("especie");

                    b.Property<DateTimeOffset?>("InativadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inativado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("ObservacaoCadastral")
                        .HasColumnType("text")
                        .HasColumnName("observacao_cadastral");

                    b.Property<string>("Raca")
                        .HasColumnType("text")
                        .HasColumnName("raca");

                    b.Property<int>("Sexo")
                        .HasColumnType("integer")
                        .HasColumnName("sexo");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TutorResponsavelId")
                        .HasColumnType("uuid")
                        .HasColumnName("tutor_responsavel_id");

                    b.Property<int>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("versao");

                    b.HasKey("Id")
                        .HasName("pk_animais");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_animais_tenant_id_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_animais_tenant_id");

                    b.HasIndex("TenantId", "TutorResponsavelId")
                        .HasDatabaseName("ix_animais_tenant_id_tutor_responsavel_id");

                    b.ToTable("animais", null, t =>
                        {
                            t.HasCheckConstraint("ck_animais_cor_ou_pelagem_not_blank", "cor_ou_pelagem IS NULL OR length(btrim(cor_ou_pelagem)) > 0");

                            t.HasCheckConstraint("ck_animais_data_falecimento_situacao", "(situacao = 3 AND data_do_falecimento IS NOT NULL) OR (situacao <> 3 AND data_do_falecimento IS NULL)");

                            t.HasCheckConstraint("ck_animais_especie_not_blank", "length(btrim(especie)) > 0");

                            t.HasCheckConstraint("ck_animais_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_animais_nome_not_blank", "length(btrim(nome)) > 0");

                            t.HasCheckConstraint("ck_animais_observacao_cadastral_not_blank", "observacao_cadastral IS NULL OR length(btrim(observacao_cadastral)) > 0");

                            t.HasCheckConstraint("ck_animais_raca_not_blank", "raca IS NULL OR length(btrim(raca)) > 0");

                            t.HasCheckConstraint("ck_animais_sexo", "sexo IN (0, 1, 2)");

                            t.HasCheckConstraint("ck_animais_situacao", "situacao IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_animais_tenant_id_not_empty", "tenant_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_animais_tutor_responsavel_id_not_empty", "tutor_responsavel_id <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("PetShop.Tutores.Domain.TransferenciaDeResponsabilidadeDoAnimal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<DateTimeOffset>("RealizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("realizada_em");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TutorAnteriorId")
                        .HasColumnType("uuid")
                        .HasColumnName("tutor_anterior_id");

                    b.Property<Guid>("TutorNovoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tutor_novo_id");

                    b.HasKey("Id")
                        .HasName("pk_historico_transferencias_animais");

                    b.HasIndex("TenantId", "TutorAnteriorId")
                        .HasDatabaseName("ix_hist_transf_animais_tenant_tutor_anterior");

                    b.HasIndex("TenantId", "TutorNovoId")
                        .HasDatabaseName("ix_hist_transf_animais_tenant_tutor_novo");

                    b.HasIndex("TenantId", "AnimalId", "RealizadaEm")
                        .HasDatabaseName("ix_historico_transferencias_animais_tenant_animal_data");

                    b.ToTable("historico_transferencias_animais", null, t =>
                        {
                            t.HasCheckConstraint("ck_historico_transferencias_animais_animal_id_not_empty", "animal_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_historico_transferencias_animais_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_historico_transferencias_animais_motivo_not_blank", "motivo IS NULL OR length(btrim(motivo)) > 0");

                            t.HasCheckConstraint("ck_historico_transferencias_animais_subject_not_blank", "length(btrim(subject)) > 0");

                            t.HasCheckConstraint("ck_historico_transferencias_animais_tenant_id_not_empty", "tenant_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_historico_transferencias_animais_tutor_anterior_not_empty", "tutor_anterior_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_historico_transferencias_animais_tutor_novo_not_empty", "tutor_novo_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_historico_transferencias_animais_tutores_diferentes", "tutor_anterior_id <> tutor_novo_id");
                        });
                });

            modelBuilder.Entity("PetShop.Tutores.Domain.Tutor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Documento")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("InativadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inativado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.Property<string>("Telefone")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("telefone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tutores");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_tutores_tenant_id_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tutores_tenant_id");

                    b.HasIndex("TenantId", "Documento")
                        .IsUnique()
                        .HasDatabaseName("ix_tutores_tenant_id_documento");

                    b.ToTable("tutores", null, t =>
                        {
                            t.HasCheckConstraint("ck_tutores_contato_obrigatorio", "email IS NOT NULL OR telefone IS NOT NULL");

                            t.HasCheckConstraint("ck_tutores_documento_len", "documento IS NULL OR length(documento) = 11");

                            t.HasCheckConstraint("ck_tutores_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_tutores_situacao", "situacao IN (1, 2)");

                            t.HasCheckConstraint("ck_tutores_telefone_len", "telefone IS NULL OR length(telefone) IN (10, 11)");

                            t.HasCheckConstraint("ck_tutores_tenant_id_not_empty", "tenant_id <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("PetShop.Tutores.Domain.Animal", b =>
                {
                    b.HasOne("PetShop.Tutores.Domain.Tutor", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TutorResponsavelId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_animais_tutores_tenant_id_tutor_responsavel_id");
                });

            modelBuilder.Entity("PetShop.Tutores.Domain.TransferenciaDeResponsabilidadeDoAnimal", b =>
                {
                    b.HasOne("PetShop.Tutores.Domain.Animal", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "AnimalId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hist_transf_animais_animais_tenant_id_animal_id");

                    b.HasOne("PetShop.Tutores.Domain.Tutor", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TutorAnteriorId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hist_transf_animais_tutores_tenant_id_tutor_anterior_id");

                    b.HasOne("PetShop.Tutores.Domain.Tutor", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TutorNovoId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hist_transf_animais_tutores_tenant_id_tutor_novo_id");
                });
#pragma warning restore 612, 618
        }
    }
}
